version: '2'

services:
  puppet:
    container_name: puppet
    hostname: puppet
    image: puppet/puppetserver
    ports:
      - 0.0.0.0:8140:8140
    volumes:
      - ./code:/etc/puppetlabs/code/
    # In some cases unqualified hostnames can have the .local suffix
    # added, I've seen this under Docker of Mac Beta for instance.
    # Due to needing to access PuppetDB on same hostame as signed in the
    # certificate you may need to uncommant the following lines
    environment:
      - PUPPETDB_SERVER_URLS=https://puppetdb.localdomain:8081
    links:
      - puppetdb:puppetdb.localdomain

  puppetdbpostgres:
    container_name: postgres
    image: puppet/puppetdb-postgres
    environment:
      - POSTGRES_PASSWORD=puppetdb
      - POSTGRES_USER=puppetdb
    expose:
      - 5432

  puppetdb:
    hostname: puppetdb
    image: puppet/puppetdb
    ports:
      - 0.0.0.0:8080:8080
      - 0.0.0.0:8081:8081

  puppetboard:
    image: puppet/puppetboard
    ports:
      - 0.0.0.0:8000:8000

  puppetexplorer:
    image: puppet/puppetexplorer
    ports:
      - 0.0.0.0:80:80
    read_only: true
